spring:
  application:
    name: sdv-auth-api
  datasource:
    url: jdbc:postgresql://localhost:5432/sdv-auth-api
    username: pascallim
    password:
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8083

jwt:
  secret: 6QNR9BfF9PpJWrFBNcCQVYRJUbCpQeRd6hIlXLvYhA4=
  expiration: 86400

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
