spring:
  application:
    name: sdv-student-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sdv-student-api
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
