spring:
  application:
    name: sdv-school-api
  datasource:
    url: jdbc:postgresql://localhost:5432/sdv-school-api
    username: pascallim
    password: ""
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
